name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        node-version: [
            16.0.0
            16.1.0,
            16.2.0,
            16.3.0,
            16.4.0,
            16.4.1,
            16.4.2,
            16.5.0,
            16.6.0,
            16.6.1,
            16.6.2,
            16.7.0,
            16.8.0,
            16.9.0,
            16.9.1,
            16.10.0,
            16.11.0,
            16.11.1,
            16.12.0,
            16.13.0,
            16.13.1,
            16.13.2,
            16.14.0,
            16.14.1,
            16.14.2,
            16.15.0,
            16.15.1,
            16.16.0,
            16.17.0,
            16.17.1,
            16.18.0,
            16.18.1,
            16.19.0,
            16.19.1,
            16.20.0,
            16.20.1,
            16.20.2,
            18.0.0,
            20.0.0,
            21.0.0,
          ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm install next
      - run: npm start
